#!/bin/sh
set -e

if [ -n "$POSTGRES_REPLICATOR_PASSWORD_FILE" ]; then
    POSTGRES_REPLICATOR_PASSWORD=$(cat "$POSTGRES_REPLICATOR_PASSWORD_FILE")
fi

if [ -n "${POSTGRES_REPLICATOR_PASSWORD}" ]; then
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
        CREATE ROLE ${POSTGRES_REPLICATOR_NAME:-replicator}
            WITH REPLICATION LOGIN PASSWORD '${POSTGRES_REPLICATOR_PASSWORD}';
EOSQL
fi
